/**
 * Octo-Juggler Layer Configuration
 * The order of the keys defines the stacking order (the last one is on top).
 */
module.exports = {
  layers: {
    "background": {
      "🏖️": "beach_small.png",
      "🌊": "beach_small.png",
      "🌴": "beach_small.png",
      "⛱️": "beach_small.png",
      "🏄": "beach_small.png",
      "🏊": "beach_small.png",
      "🚤": "beach_small.png",
      "🐚": "beach_small.png",
      "🍍": "beach_small.png",
      "🍹": "beach_small.png",
      "🏠": "home_small.png",
      "🏡": "home_small.png",
      "🏘️": "home_small.png",
      "💻": "home_small.png",
      "🖥️": "home_small.png",
      "🛋️": "home_small.png",
      "🏢": "home_small.png",
      "🤒": "home_small.png",
      "🤢": "home_small.png",
      "🤮": "home_small.png",
      "😷": "home_small.png",
      "🤕": "home_small.png",
      "🌡️": "home_small.png",
      "🏔️": "mountain_small.png",
      "⛰️": "mountain_small.png",
      "🌋": "mountain_small.png",
      "🌲": "mountain_small.png",
      "🌳": "mountain_small.png",
      "🏕️": "mountain_small.png",
      "⛺": "mountain_small.png",
      "🧗": "mountain_small.png",
      "🎿": "mountain_small.png",
      "🏂": "mountain_small.png",
      "default": "sticker_small.png"
    },
    "body": "body_small.png",
    "face": "face_small.png",
    "mouth": {
      "🤒": "sick_small.png",
      "🤢": "sick_small.png",
      "🤮": "sick_small.png",
      "😷": "sick_small.png",
      "🤕": "sick_small.png",
      "🌡️": "sick_small.png",
      "🙂": "smile_small.png",
      "😄": "smile_small.png",
      "😁": "smile_small.png",
      "😊": "smile_small.png",
      "😃": "smile_small.png",
      "😍": "smile_small.png",
      "🥳": "smile_small.png",
      "✨": "smile_small.png",
      "🚀": "smile_small.png",
      "🙁": "sad_small.png",
      "☹️": "sad_small.png",
      "😢": "sad_small.png",
      "😭": "sad_small.png",
      "💔": "sad_small.png",
      "🌧️": "sad_small.png",
      "0": "sad_small.png",
      "1": "default_small.png",
      "+": "smile_small.png",
      "default": "smile_small.png"
    },
    "eyes": {
      "😎": "sunglasses_small.png",
      "🕶️": "sunglasses_small.png",
      "☀️": "sunglasses_small.png",
      "🌞": "sunglasses_small.png",
      "🚢": "sunglasses_small.png",
      "🏴‍☠️": "pirate_small.png",
      "🦜": "pirate_small.png",
      "⚓": "pirate_small.png",
      "⚔️": "pirate_small.png",
      "🗺️": "pirate_small.png",
      "😉": "wink_small.png",
      "😜": "wink_small.png",
      "🤑": "wink_small.png",
      "👻": "wink_small.png",
      "default": "default_small.png"
    },
    "arms": {
      "1": "1-arm-down_small.png",
      "2": "2-arms_small.png",
      "3": "2-arms_small.png",
      "4": "3-arms_small.png",
      "5": "3-arms_small.png",
      "6": "3-arms_small.png",
      "7": "3-arms_small.png",
      "+": "4-arms_small.png"
    },
    "balls": {
      "1": "1-ball_small.png",
      "2": "2-balls_small.png",
      "3": "3-balls_small.png",
      "4": "4-balls_small.png",
      "5": "5-balls_small.png",
      "6": "6-balls_small.png",
      "7": "7-balls_small.png",
      "8": "8-balls_small.png",
      "+": "9-balls_small.png"
    }
  }
};
